feat: Add active external Visio connector to profile property settings list - EXO-69942
exoplatform/external-visio-connector pull request #16
Opened 2024-02-28 15:16 UTC by IlhemEssaadi

This commit adds the external Visio connectors active for users to the list of profile property settings.

2024-02-28 17:23 UTC, rdenarie requested changes
I think the part about deactivation is missing.
Or do you make it in another PR

2024-02-28 17:23 UTC, rdenarie commented on services/src/main/java/org/exoplatform/webconferencing/externalvisio/service/impl/ExternalVisioConnectorServiceImpl.java
> +  public ExternalVisioConnector createExternalVisioConnector(ExternalVisioConnectorEntity externalVisioConnectorEntity) throws ObjectAlreadyExistsException {
why throwing the error here ?
if the setting property exists, so it is ok, catch the error, log a warn, and continue.
No need to propagate the error

2024-02-28 17:23 UTC, rdenarie commented on services/src/main/java/org/exoplatform/webconferencing/externalvisio/service/impl/ExternalVisioConnectorServiceImpl.java
> +  public ExternalVisioConnector updateExternalVisioConnector(ExternalVisioConnectorEntity externalVisioConnectorEntity) throws ObjectNotFoundException,
same here, no need to propagate the errror

2024-02-29 08:54 UTC, IlhemEssaadi commented
> I think the part about deactivation is missing. Or do you make it in another PR

Already treated in the updateExternalVisioConnector method.

2024-02-29 08:58 UTC, rdenarie approved these changes

2024-02-29 09:10 UTC, merged